### GET ALL Account
GET https://localhost:7098/Account

### GET Account By ID
GET https://localhost:7098/Account/4

### DELETE Account
DELETE https://localhost:7098/Account
Content-Type: application/json

{
  "Id": 6
}

### REGISTER Account
POST https://localhost:7098/Account
Content-Type: application/json

{
  "username": "patrick",
  "password": "123456",
  "mail": "patrick@mail.com"
}

### UPDATE Account
PUT https://localhost:7098/Account/10
Content-Type: application/json

{
  "Id": 10,
  "username": "patrick",
  "password": "123456",
  "mail": "patrick4@mail.com",
  "isAdmin": false
}